// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/domain/model/event_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 4453571201750822153),
      name: 'EventModel',
      lastPropertyId: const IdUid(4, 6672772173851541605),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(id: const IdUid(1, 3147299938593019452), name: 'id', type: 6, flags: 1),
        ModelProperty(id: const IdUid(2, 3374948790574269620), name: 'name', type: 9, flags: 0),
        ModelProperty(id: const IdUid(3, 6436681634393945622), name: 'date', type: 10, flags: 0),
        ModelProperty(id: const IdUid(4, 6672772173851541605), name: 'isDone', type: 1, flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 4453571201750822153),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    EventModel: EntityDefinition<EventModel>(
        model: _entities[0],
        toOneRelations: (EventModel object) => [],
        toManyRelations: (EventModel object) => {},
        getId: (EventModel object) => object.id,
        setId: (EventModel object, int id) {
          object.id = id;
        },
        objectToFB: (EventModel object, fb.Builder fbb) {
          final nameOffset = object.content == null ? null : fbb.writeString(object.content!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.date?.millisecondsSinceEpoch);
          fbb.addBool(3, object.isDone);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateValue = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final object = EventModel(
              content: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              date: dateValue == null ? null : DateTime.fromMillisecondsSinceEpoch(dateValue),
              isDone: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 10))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [EventModel] entity fields to define ObjectBox queries.
class EventModel_ {
  /// see [EventModel.id]
  static final id = QueryIntegerProperty<EventModel>(_entities[0].properties[0]);

  /// see [EventModel.content]
  static final name = QueryStringProperty<EventModel>(_entities[0].properties[1]);

  /// see [EventModel.date]
  static final date = QueryIntegerProperty<EventModel>(_entities[0].properties[2]);

  /// see [EventModel.isDone]
  static final isDone = QueryBooleanProperty<EventModel>(_entities[0].properties[3]);
}
